---
title: Fast Forward Labs Blog
timezone: UTC
collections:
  links:
    title: Links
    output: false
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: your-email@domain.com
description: 'Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.

'
baseurl: ''
url: ''
twitter_username: jekyllrb
github_username: jekyll
markdown: kramdown
excerpt_separator: "\\n\\n"
gems:
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
